const infoStyles = {
  'info-container': [
    'absolute',
    'z-40',
    // 'left-8',
    'top-48',
    'w-full',
    'h-80',
    'xl:h-44',
  ].join(' '),
  'info-wrapper': [
    'xl:h-full',
    'xl:text-left',
    'lg:text-left',
    'text-center',
    'flex',
    'items-center',
    'justify-center',
  ].join(' '),
  'info-list-wrapper': [
    'w-full',
    'bg-white',
    'shadow-xl',
    'rounded-xl',
    'px-2',
    'py-5',
    'flex',
    'flex-col',
    'justify-center',
    'items-center',
    'xl:flex-row',
    'lg:flex-row',
    'gap-4',
    'flex-none',
    'xl:basis-2/4',
    'lg:basis-3/5',
    'md:basis-3/5',
    'sm:basis-3/5',
    'basis-11/12',
    'shrink',
  ].join(' '),
  infoWarning: [
    'py-4',
    'pl-3',
    'text-red-600',
    'text-2xl',
  ].join(' '),
  infoValid: [
    'py-4',
    'pl-3',
    'text-xl',
    'text-vdgray',
  ].join(' '),
};

export default infoStyles;
