const infoStyles = {
  'info-container': [
    'absolute',
    'z-40',
    // 'left-8',
    'top-48',
    'w-full',
    'h-80',
    'xl:h-44',
  ].join(' '),
  'info-wrapper': [
    'xl:h-full',
    'xl:text-left',
    'lg:text-left',
    'text-center',
    'flex',
    'items-center',
    'justify-center',
  ].join(' '),
  'info-list-wrapper': [
    'w-full',
    'bg-white',
    'shadow-xl',
    'rounded-xl',
    'px-2',
    'py-5',
    'flex',
    'flex-col',
    'justify-evenly',
    'xl:flex-row',
    'lg:flex-row',
    'gap-4',
    'flex-none',
    'xl:basis-3/4',
    'lg:basis-4/5',
    'md:basis-4/5',
    'sm:basis-4/5',
    'basis-11/12',
    'shrink',
  ].join(' '),
  infoText: [
    'font-medium',
    'text-vdgray',
    'xl:text-2xl',
    'break-words',
    'xl:w-48',
    'lg:w-52',
    'pr-3',
  ].join(' '),
  infoWarning: [
    'py-4',
    'pl-3',
    'text-red-600',
    'text-2xl',
  ].join(' '),
  infoValid: [
    'py-4',
    'pl-3',
    'text-xl',
    'text-vdgray',
  ].join(' '),
  infoList: [
    'list-none',
  ].join(' '),
  infoLabel: [
    'text-dgray',
    'text-xxs',
    'sm:text-sm',
    'xl:text-base',
    'font-semibold',
    'xl:font-bold',
    'lg:font-bold',
    'tracking-wide',
    'xl:mb-2',
    'lg:mb-2',
  ].join(' '),
  infoListFlex: [
    'flex',
    'flex-col',
  ].join(' '),
};

export default infoStyles;
